### PR TITLE
Fixed JSONorText Logic check to application/json line 27

### PR DESCRIPTION
**Pull request by zachhadel**
### Checklist

-   [x] If code changes were made then they have been tested
    -   [ ] I have updated the documentation to reflect the changes
-   [x] This Pull Request fixes an Issue
-   [ ] This Pull Request adds something new (e.g. new method or parameters)
-   [ ] This Pull Request is a breaking change (e.g. methods or parameters removed/renamed)
-   [ ] This Pull Request is not a code change (e.g. Documentation or README)

### CODE REVIEW

**Comment by zachhadel** [comment]
Cool project!

**Comment by zachhadel** [comment]
Cool project!

**Comment by EthanC** [comment]
@zachhadel Where are you seeing `application/json` used? I've specifically set it to check for `application/json;charset=utf-8` because that's the only content-type I've seen the Call of Duty API use.

**Comment by zachhadel** [comment]
@EthanC 

I am using it on:
Title.ModernWarfare, Mode.Multiplayer

Also, "wz" or Mode.Blackout works with Title.ModernWarfare now. I disabled the verify functions, and I am getting data back.

All the API calls were giving back strings, and the package would break when any key was called on the json.

ex:
json_to_str["data"]

gives error "TypeError: 'int' object is not subscriptable"
because the json was passed as an int when the header != application/json;charset=utf-8

**Comment by tyeoneill** [comment]
This works for me, I was having the JSON string issue.

**Pull request closed without merging**
